// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SosuBot.Database.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20250425205823_AddOsuUsers")]
    partial class AddOsuUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("SosuBot.Database.Models.OsuUser", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OsuUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsuUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PPValue")
                        .HasColumnType("REAL");

                    b.HasKey("TelegramId");

                    b.ToTable("OsuUsers");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TelegramChat", b =>
                {
                    b.Property<ulong>("ChatId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ChatMembers")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastBeatmapId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.ToTable("TelegramChats");
                });
#pragma warning restore 612, 618
        }
    }
}
