// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SosuBot.Database.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20250428080240_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SosuBot.Database.Models.OsuUser", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CatchPPValue")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ManiaPPValue")
                        .HasColumnType("REAL");

                    b.Property<int>("OsuMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OsuUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsuUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StdPPValue")
                        .HasColumnType("REAL");

                    b.Property<double>("TaikoPPValue")
                        .HasColumnType("REAL");

                    b.HasKey("TelegramId");

                    b.ToTable("OsuUsers");

                    b.HasData(
                        new
                        {
                            TelegramId = 0L,
                            CatchPPValue = 0.0,
                            IsAdmin = false,
                            ManiaPPValue = 0.0,
                            OsuMode = 0,
                            OsuUserId = 15319810L,
                            OsuUsername = "Shoukko",
                            StdPPValue = 0.0,
                            TaikoPPValue = 0.0
                        });
                });

            modelBuilder.Entity("SosuBot.Database.Models.TelegramChat", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ChatMembers")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ExcludeFromChatstats")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastBeatmapId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.ToTable("TelegramChats");
                });
#pragma warning restore 612, 618
        }
    }
}
