services:
  prometheus:
    network_mode: host
    networks: !reset []
    ports: !reset []
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --web.listen-address=127.0.0.1:9090
    volumes:
      - ./monitoring/prometheus/prometheus.debug.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    network_mode: host
    networks: !reset []
    ports: !reset []
    environment:
      GF_SERVER_HTTP_ADDR: "127.0.0.1"
    volumes:
      - ./monitoring/grafana/debug/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
