// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SosuBot.Database;
using SosuBot.Helpers.Types;

#nullable disable

namespace SosuBot.Migrations
{
    [DbContext(typeof(BotContext))]
    partial class BotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "playmode", new[] { "catch", "mania", "osu", "taiko" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyStatisticsUserEntity", b =>
                {
                    b.Property<int>("ActiveUsersUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DailyStatisticsId")
                        .HasColumnType("integer");

                    b.HasKey("ActiveUsersUserId", "DailyStatisticsId");

                    b.HasIndex("DailyStatisticsId");

                    b.ToTable("DailyStatisticsUserEntity");
                });

            modelBuilder.Entity("SosuBot.Database.Models.DailyStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<int>>("BeatmapsPlayed")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DayOfStatistic")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DailyStatistics");
                });

            modelBuilder.Entity("SosuBot.Database.Models.OsuUser", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<double>("CatchPPValue")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<double>("ManiaPPValue")
                        .HasColumnType("double precision");

                    b.Property<Playmode>("OsuMode")
                        .HasColumnType("playmode");

                    b.Property<long>("OsuUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("OsuUsername")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<double>("StdPPValue")
                        .HasColumnType("double precision");

                    b.Property<double>("TaikoPPValue")
                        .HasColumnType("double precision");

                    b.HasKey("TelegramId");

                    b.ToTable("OsuUsers");

                    b.HasData(
                        new
                        {
                            TelegramId = 728384906L,
                            CatchPPValue = 0.0,
                            IsAdmin = true,
                            ManiaPPValue = 0.0,
                            OsuMode = Playmode.Osu,
                            OsuUserId = 15319810L,
                            OsuUsername = "Shoukko",
                            StdPPValue = 0.0,
                            TaikoPPValue = 0.0
                        });
                });

            modelBuilder.Entity("SosuBot.Database.Models.ScoreEntity", b =>
                {
                    b.Property<long>("ScoreId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DailyStatisticsId")
                        .HasColumnType("integer");

                    b.Property<string>("ScoreJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ScoreId");

                    b.HasIndex("DailyStatisticsId");

                    b.ToTable("ScoreEntity");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TelegramChat", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<long>>("ChatMembers")
                        .HasColumnType("bigint[]");

                    b.PrimitiveCollection<List<long>>("ExcludeFromChatstats")
                        .HasColumnType("bigint[]");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastBeatmapId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<int>>("TrackedPlayers")
                        .HasColumnType("integer[]");

                    b.HasKey("ChatId");

                    b.ToTable("TelegramChats");
                });

            modelBuilder.Entity("SosuBot.Database.Models.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("UserId");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("DailyStatisticsUserEntity", b =>
                {
                    b.HasOne("SosuBot.Database.Models.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ActiveUsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SosuBot.Database.Models.DailyStatistics", null)
                        .WithMany()
                        .HasForeignKey("DailyStatisticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SosuBot.Database.Models.ScoreEntity", b =>
                {
                    b.HasOne("SosuBot.Database.Models.DailyStatistics", null)
                        .WithMany("Scores")
                        .HasForeignKey("DailyStatisticsId");
                });

            modelBuilder.Entity("SosuBot.Database.Models.DailyStatistics", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
