// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SosuBot.Database;
using SosuBot.Database.Models;

#nullable disable

namespace SosuBot.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20251028160409_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "playmode", new[] { "catch", "mania", "osu", "taiko" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SosuBot.Database.Models.OsuUser", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<double>("CatchPPValue")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<double>("ManiaPPValue")
                        .HasColumnType("double precision");

                    b.Property<Playmode>("OsuMode")
                        .HasColumnType("playmode");

                    b.Property<long>("OsuUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("OsuUsername")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<double>("StdPPValue")
                        .HasColumnType("double precision");

                    b.Property<double>("TaikoPPValue")
                        .HasColumnType("double precision");

                    b.HasKey("TelegramId");

                    b.ToTable("OsuUsers");

                    b.HasData(
                        new
                        {
                            TelegramId = 728384906L,
                            CatchPPValue = 0.0,
                            IsAdmin = true,
                            ManiaPPValue = 0.0,
                            OsuMode = Playmode.Osu,
                            OsuUserId = 15319810L,
                            OsuUsername = "Shoukko",
                            StdPPValue = 0.0,
                            TaikoPPValue = 0.0
                        });
                });

            modelBuilder.Entity("SosuBot.Database.Models.TelegramChat", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<long>>("ChatMembers")
                        .HasColumnType("bigint[]");

                    b.PrimitiveCollection<List<long>>("ExcludeFromChatstats")
                        .HasColumnType("bigint[]");

                    b.Property<int?>("LastBeatmapId")
                        .HasColumnType("integer");

                    b.HasKey("ChatId");

                    b.ToTable("TelegramChats");
                });
#pragma warning restore 612, 618
        }
    }
}
