// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SosuBot.Database;
using SosuBot.Database.Models;

#nullable disable

namespace SosuBot.Migrations
{
    [DbContext(typeof(BotContext))]
    partial class BotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "playmode", new[] { "catch", "mania", "osu", "taiko" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyStatisticsUserEntity", b =>
                {
                    b.Property<int>("ActiveUsersUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DailyStatisticsId")
                        .HasColumnType("integer");

                    b.HasKey("ActiveUsersUserId", "DailyStatisticsId");

                    b.HasIndex("DailyStatisticsId");

                    b.ToTable("DailyStatisticsUserEntity");
                });

            modelBuilder.Entity("SosuBot.Database.Models.CommandUsageAggregate", b =>
                {
                    b.Property<string>("Command")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("BucketStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CancelledCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDurationMilliseconds")
                        .HasColumnType("bigint");

                    b.HasKey("Command", "BucketStartUtc");

                    b.HasIndex("BucketStartUtc");

                    b.ToTable("CommandUsageAggregates");
                });

            modelBuilder.Entity("SosuBot.Database.Models.DailyStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<int>>("BeatmapsPlayed")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DayOfStatistic")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DailyStatistics");
                });

            modelBuilder.Entity("SosuBot.Database.Models.DailyStatisticsReportDelivery", b =>
                {
                    b.Property<int>("DailyStatisticsId")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DailyStatisticsId", "Mode");

                    b.HasIndex("AvailableAtUtc", "LockedUntilUtc")
                        .HasDatabaseName("IX_DailyStatisticsReportDeliveries_Pending")
                        .HasFilter("\"SentAtUtc\" IS NULL AND \"CancelledAtUtc\" IS NULL AND \"FailedAtUtc\" IS NULL");

                    b.ToTable("DailyStatisticsReportDeliveries");
                });

            modelBuilder.Entity("SosuBot.Database.Models.OsuUser", b =>
                {
                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<double>("CatchPPValue")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<double>("ManiaPPValue")
                        .HasColumnType("double precision");

                    b.Property<Playmode>("OsuMode")
                        .HasColumnType("playmode");

                    b.Property<long>("OsuUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("OsuUsername")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("RenderSettings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("StdPPValue")
                        .HasColumnType("double precision");

                    b.Property<double>("TaikoPPValue")
                        .HasColumnType("double precision");

                    b.HasKey("TelegramId");

                    b.ToTable("OsuUsers");

                    b.HasData(
                        new
                        {
                            TelegramId = 728384906L,
                            CatchPPValue = 0.0,
                            IsAdmin = true,
                            ManiaPPValue = 0.0,
                            OsuMode = Playmode.Osu,
                            OsuUserId = 15319810L,
                            OsuUsername = "Shoukko",
                            RenderSettings = "{\"VideoWidth\":1280,\"VideoHeight\":720,\"Encoder\":\"h264_nvenc\",\"SkinName\":\"default\",\"GeneralVolume\":0.5,\"MusicVolume\":0.5,\"SampleVolume\":0.5,\"BackgroundDim\":0.95,\"CursorSize\":1,\"SkipIntro\":true,\"HitErrorMeter\":true,\"AimErrorMeter\":false,\"HPBar\":true,\"ShowPP\":true,\"HitCounter\":true,\"IgnoreFailsInReplays\":false,\"Video\":false,\"Storyboard\":false,\"Mods\":true,\"KeyOverlay\":true,\"Combo\":true,\"Leaderboard\":false,\"StrainGraph\":true,\"MotionBlur\":false,\"UseExperimentalRenderer\":false,\"ManiaScrollSpeed\":25,\"ManiaScrollDirectionUp\":false}",
                            StdPPValue = 0.0,
                            TaikoPPValue = 0.0
                        });
                });

            modelBuilder.Entity("SosuBot.Database.Models.ScoreEntity", b =>
                {
                    b.Property<long>("ScoreId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DailyStatisticsId")
                        .HasColumnType("integer");

                    b.Property<string>("ScoreJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ScoreId");

                    b.HasIndex("DailyStatisticsId");

                    b.ToTable("ScoreEntity");
                });

            modelBuilder.Entity("SosuBot.Database.Models.ScoreFeedCheckpoint", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Cursor")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Source");

                    b.ToTable("ScoreFeedCheckpoints");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TelegramChat", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<long>>("ChatMembers")
                        .HasColumnType("bigint[]");

                    b.PrimitiveCollection<List<long>>("ExcludeFromChatstats")
                        .HasColumnType("bigint[]");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LastBeatmapId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<int>>("TrackedPlayers")
                        .HasColumnType("integer[]");

                    b.HasKey("ChatId");

                    b.ToTable("TelegramChats");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TrackedPlayerCheckpoint", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<long>>("BestScoreIds")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Mode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId");

                    b.ToTable("TrackedPlayerCheckpoints");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TrackedPlayerSubscription", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChatId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("TrackedPlayerSubscriptions");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TrackedScoreDelivery", b =>
                {
                    b.Property<long>("ScoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdminRecipient")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScoreId", "ChatId");

                    b.HasIndex("AvailableAtUtc", "LockedUntilUtc")
                        .HasDatabaseName("IX_TrackedScoreDeliveries_Pending")
                        .HasFilter("\"SentAtUtc\" IS NULL AND \"CancelledAtUtc\" IS NULL AND \"FailedAtUtc\" IS NULL");

                    b.ToTable("TrackedScoreDeliveries");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TrackedScoreEvent", b =>
                {
                    b.Property<long>("ScoreId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("ScoreJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ScoreId");

                    b.HasIndex("PlayerId", "OccurredAtUtc");

                    b.ToTable("TrackedScoreEvents");
                });

            modelBuilder.Entity("SosuBot.Database.Models.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("UserId");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("DailyStatisticsUserEntity", b =>
                {
                    b.HasOne("SosuBot.Database.Models.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ActiveUsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SosuBot.Database.Models.DailyStatistics", null)
                        .WithMany()
                        .HasForeignKey("DailyStatisticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SosuBot.Database.Models.DailyStatisticsReportDelivery", b =>
                {
                    b.HasOne("SosuBot.Database.Models.DailyStatistics", "DailyStatistics")
                        .WithMany()
                        .HasForeignKey("DailyStatisticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyStatistics");
                });

            modelBuilder.Entity("SosuBot.Database.Models.ScoreEntity", b =>
                {
                    b.HasOne("SosuBot.Database.Models.DailyStatistics", null)
                        .WithMany("Scores")
                        .HasForeignKey("DailyStatisticsId");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TrackedPlayerSubscription", b =>
                {
                    b.HasOne("SosuBot.Database.Models.TelegramChat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TrackedScoreDelivery", b =>
                {
                    b.HasOne("SosuBot.Database.Models.TrackedScoreEvent", "Event")
                        .WithMany("Deliveries")
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SosuBot.Database.Models.DailyStatistics", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("SosuBot.Database.Models.TrackedScoreEvent", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
